# connection settings

# if you need to seed an index from a collection and not just listen and sync changes events
# you can copy entire collections or views from MongoDB to Elasticsearch
direct-read-namespaces = [
    "OpenSitexDev.users",
    "OpenSitexDev.domains",
    "OpenSitexDev.storeproducts",
    "OpenSitexDev.storedomains",
    "OpenSitexDev.stores",
    "OpenSitexDev.orders",
    "OpenSitexDev.orderitems",
    "OpenSitexDev.productpages",
    "OpenSitexDev.utms",
    "OpenSitexDev.views",
    "OpenSitexDev.trackinghistories",
    "OpenSitexDev.galleries",
    "OpenSitexDev.products",
]

# if you want to use MongoDB change streams instead of legacy oplog tailing use change-stream-namespaces
# change streams require at least MongoDB API 3.6+
# if you have MongoDB 4+ you can listen for changes to an entire database or entire deployment
# in this case you usually don't need regexes in your config to filter collections unless you target the deployment.
# to listen to an entire db use only the database name.  For a deployment use an empty string.
change-stream-namespaces = [
    "OpenSitexDev.users",
    "OpenSitexDev.domains",
    "OpenSitexDev.storeproducts",
    "OpenSitexDev.storedomains",
    "OpenSitexDev.stores",
    "OpenSitexDev.orders",
    "OpenSitexDev.orderitems",
    "OpenSitexDev.productpages",
    "OpenSitexDev.utms",
    "OpenSitexDev.views",
    "OpenSitexDev.trackinghistories",
    "OpenSitexDev.galleries",
    "OpenSitexDev.products",
]

# additional settings

# compress requests to Elasticsearch
gzip = true
# generate indexing statistics
stats = false
# index statistics into Elasticsearch
index-stats = false
# use the following user name for Elasticsearch basic auth
elasticsearch-max-conns = 10
# use the following PEM file to connections to Elasticsearch
elasticsearch-pem-file = "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
# validate connections to Elasticsearch
elasticsearch-validate-pem-file = true
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = true
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = true
# do not start processing at the beginning of the MongoDB oplog
# if you set the replay to true you may see version conflict messages
# in the log if you had synced previously. This just means that you are replaying old docs which are already
# in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
replay = false
# resume processing from a timestamp saved in a previous run
resume = true
# do not validate that progress timestamps have been saved
resume-write-unsafe = false
# override the name under which resume state is saved
resume-name = "default"
# use a custom resume strategy (tokens) instead of the default strategy (timestamps)
# tokens work with MongoDB API 3.6+ while timestamps work only with MongoDB API 4.0+
resume-strategy = 1
verbose = true
# do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false

########################################
# xác định collection được mapping từ mongodb sang ES
[[mapping]]
namespace = "OpenSitexDev.users"
index = "users"

[[mapping]]
namespace = "OpenSitexDev.domains"
index = "domains"

[[mapping]]
namespace = "OpenSitexDev.storeproducts"
index = "storeproducts"

[[mapping]]
namespace = "OpenSitexDev.storedomains"
index = "storedomains"

[[mapping]]
namespace = "OpenSitexDev.stores"
index = "stores"

[[mapping]]
namespace = "OpenSitexDev.orders"
index = "orders"

[[mapping]]
namespace = "OpenSitexDev.orderitems"
index = "orderitems"

[[mapping]]
namespace = "OpenSitexDev.productpages"
index = "productpages"

[[mapping]]
namespace = "OpenSitexDev.utms"
index = "utms"

[[mapping]]
namespace = "OpenSitexDev.views"
index = "views"

[[mapping]]
namespace = "OpenSitexDev.trackinghistories"
index = "trackinghistories"

[[mapping]]
namespace = "OpenSitexDev.products"
index = "products"

[[mapping]]
namespace = "OpenSitexDev.galleries"
index = "galleries"

########################################
# Lọc các bản ghi trước khi đánh index (nếu bạn không cần lọc thì có thể bỏ qua phần này)
# đọc thêm tại đây https://rwynn.github.io/monstache-site/advanced/#filtering
[[filter]]
path = "filter/base.js"

########################################
# script có thể dùng để chỉnh sửa dữ liệu, drop bản ghi
# [[script]]
# namespace = "OpenSitexDev.orders"
# routing = true
# path = "transform/base.js"

[[script]]
path = "transform/base.js"
routing = true
